/* -------------------------------
   Fake DCW directory for search
-------------------------------- */
const DCWS = [
  {
    id: "dcw_001",
    fullName: "Jane Ostin",
    email: "jane.ostin@gmail.com",
    address: "801 N Orange St #2",
    zip: "79830",
    city: "Alpine",
    county: "Brewster",
    state: "Texas",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (215) 076-4083"
  },
  {
    id: "dcw_002",
    fullName: "John Carter",
    email: "john.carter@agency.com",
    address: "14 Sunset Ave",
    zip: "19104",
    city: "Philadelphia",
    county: "Philadelphia",
    state: "Pennsylvania",
    homePhone: "+1 (215) 111-2222",
    workPhone: "",
    cellPhone: "+1 (215) 333-4444"
  },
  {
    id: "dcw_003",
    fullName: "Maria Lopez",
    email: "maria.lopez@care.com",
    address: "77 Pine Street",
    zip: "73301",
    city: "Austin",
    county: "Travis",
    state: "Texas",
    homePhone: "",
    workPhone: "+1 (512) 555-0101",
    cellPhone: "+1 (512) 555-0199"
  },
  {
    id: "dcw_004",
    fullName: "Alyssa Nguyen",
    email: "alyssa.nguyen@agency.com",
    address: "220 Market St",
    zip: "19106",
    city: "Philadelphia",
    county: "Philadelphia",
    state: "Pennsylvania",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (215) 555-0174"
  },
  {
    id: "dcw_005",
    fullName: "Marcus Reed",
    email: "marcus.reed@care.com",
    address: "905 Ocean Ave",
    zip: "33139",
    city: "Miami Beach",
    county: "Miami-Dade",
    state: "Florida",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (305) 555-0141"
  },
  {
    id: "dcw_006",
    fullName: "Fatima Khan",
    email: "fatima.khan@gmail.com",
    address: "18 W 34th St",
    zip: "10001",
    city: "New York",
    county: "New York",
    state: "New York",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (917) 555-0128"
  },
  {
    id: "dcw_007",
    fullName: "Luis Hernandez",
    email: "luis.hernandez@homehelp.org",
    address: "4101 Cesar Chavez St",
    zip: "94131",
    city: "San Francisco",
    county: "San Francisco",
    state: "California",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (415) 555-0133"
  },
  {
    id: "dcw_008",
    fullName: "Priya Patel",
    email: "priya.patel@agency.com",
    address: "1200 Congress Ave",
    zip: "78701",
    city: "Austin",
    county: "Travis",
    state: "Texas",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (512) 555-0120"
  },
  {
    id: "dcw_009",
    fullName: "Ethan Brooks",
    email: "ethan.brooks@care.com",
    address: "77 Walnut St",
    zip: "19103",
    city: "Philadelphia",
    county: "Philadelphia",
    state: "Pennsylvania",
    homePhone: "",
    workPhone: "+1 (215) 555-0190",
    cellPhone: "+1 (215) 555-0191"
  },
  {
    id: "dcw_010",
    fullName: "Sofia Rossi",
    email: "sofia.rossi@gmail.com",
    address: "501 5th Ave",
    zip: "10017",
    city: "New York",
    county: "New York",
    state: "New York",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (646) 555-0107"
  },
  {
    id: "dcw_011",
    fullName: "Noah Kim",
    email: "noah.kim@agency.com",
    address: "2200 Wilshire Blvd",
    zip: "90403",
    city: "Santa Monica",
    county: "Los Angeles",
    state: "California",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (310) 555-0156"
  },
  {
    id: "dcw_012",
    fullName: "Grace Chen",
    email: "grace.chen@care.com",
    address: "99 Sunset Blvd",
    zip: "90028",
    city: "Los Angeles",
    county: "Los Angeles",
    state: "California",
    homePhone: "+1 (323) 555-0102",
    workPhone: "",
    cellPhone: "+1 (323) 555-0103"
  },
  {
    id: "dcw_013",
    fullName: "Omar Ali",
    email: "omar.ali@gmail.com",
    address: "310 Bayfront Dr",
    zip: "33132",
    city: "Miami",
    county: "Miami-Dade",
    state: "Florida",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (305) 555-0198"
  },
  {
    id: "dcw_014",
    fullName: "Hannah Walker",
    email: "hannah.walker@agency.com",
    address: "44 Liberty St",
    zip: "10005",
    city: "New York",
    county: "New York",
    state: "New York",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (212) 555-0162"
  },
  {
    id: "dcw_015",
    fullName: "Diego Martinez",
    email: "diego.martinez@care.com",
    address: "800 Brickell Ave",
    zip: "33131",
    city: "Miami",
    county: "Miami-Dade",
    state: "Florida",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (786) 555-0126"
  },
  {
    id: "dcw_016",
    fullName: "Chloe Martin",
    email: "chloe.martin@gmail.com",
    address: "2101 N Lamar Blvd",
    zip: "78705",
    city: "Austin",
    county: "Travis",
    state: "Texas",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (737) 555-0139"
  },
  {
    id: "dcw_017",
    fullName: "Samuel Johnson",
    email: "samuel.johnson@agency.com",
    address: "1600 Pennsylvania Ave",
    zip: "19121",
    city: "Philadelphia",
    county: "Philadelphia",
    state: "Pennsylvania",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (215) 555-0118"
  },
  {
    id: "dcw_018",
    fullName: "Amina Hassan",
    email: "amina.hassan@care.com",
    address: "75 3rd St",
    zip: "94103",
    city: "San Francisco",
    county: "San Francisco",
    state: "California",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (415) 555-0182"
  },
  {
    id: "dcw_019",
    fullName: "Kevin O'Brien",
    email: "kevin.obrien@gmail.com",
    address: "120 King of Prussia Rd",
    zip: "19406",
    city: "King of Prussia",
    county: "Montgomery",
    state: "Pennsylvania",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (610) 555-0124"
  },
  {
    id: "dcw_020",
    fullName: "Isabella Garcia",
    email: "isabella.garcia@agency.com",
    address: "33 Broadway",
    zip: "10004",
    city: "New York",
    county: "New York",
    state: "New York",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (347) 555-0150"
  },
  {
    id: "dcw_021",
    fullName: "Mia Thompson",
    email: "mia.thompson@care.com",
    address: "2600 Collins Ave",
    zip: "33140",
    city: "Miami Beach",
    county: "Miami-Dade",
    state: "Florida",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (305) 555-0111"
  },
  {
    id: "dcw_022",
    fullName: "Benjamin Lee",
    email: "benjamin.lee@agency.com",
    address: "700 Main St",
    zip: "78702",
    city: "Austin",
    county: "Travis",
    state: "Texas",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (512) 555-0112"
  },
  {
    id: "dcw_023",
    fullName: "Zoe Williams",
    email: "zoe.williams@gmail.com",
    address: "5000 Spruce St",
    zip: "19139",
    city: "Philadelphia",
    county: "Philadelphia",
    state: "Pennsylvania",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (267) 555-0166"
  },
  {
    id: "dcw_024",
    fullName: "Jamal Carter",
    email: "jamal.carter@care.com",
    address: "901 Mission St",
    zip: "94103",
    city: "San Francisco",
    county: "San Francisco",
    state: "California",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (628) 555-0149"
  },
  {
    id: "dcw_025",
    fullName: "Tara Singh",
    email: "tara.singh@agency.com",
    address: "1601 Ocean Dr",
    zip: "33139",
    city: "Miami Beach",
    county: "Miami-Dade",
    state: "Florida",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (305) 555-0167"
  },
  {
    id: "dcw_026",
    fullName: "Nora Davis",
    email: "nora.davis@gmail.com",
    address: "35 Wall St",
    zip: "10005",
    city: "New York",
    county: "New York",
    state: "New York",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (917) 555-0189"
  },
  {
    id: "dcw_027",
    fullName: "Victor Ramirez",
    email: "victor.ramirez@care.com",
    address: "1300 Vine St",
    zip: "90028",
    city: "Los Angeles",
    county: "Los Angeles",
    state: "California",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (213) 555-0155"
  },
  {
    id: "dcw_028",
    fullName: "Elena Petrova",
    email: "elena.petrova@agency.com",
    address: "12 Park Ave",
    zip: "10016",
    city: "New York",
    county: "New York",
    state: "New York",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (646) 555-0177"
  },
  {
    id: "dcw_029",
    fullName: "Kai Nakamura",
    email: "kai.nakamura@gmail.com",
    address: "2501 S 1st St",
    zip: "78704",
    city: "Austin",
    county: "Travis",
    state: "Texas",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (512) 555-0188"
  },
  {
    id: "dcw_030",
    fullName: "Liam Murphy",
    email: "liam.murphy@care.com",
    address: "500 Chestnut St",
    zip: "19106",
    city: "Philadelphia",
    county: "Philadelphia",
    state: "Pennsylvania",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (215) 555-0179"
  },
  {
    id: "dcw_031",
    fullName: "Emily Cooper",
    email: "emily.cooper@agency.com",
    address: "1800 Collins Ave",
    zip: "33139",
    city: "Miami Beach",
    county: "Miami-Dade",
    state: "Florida",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (305) 555-0122"
  },
  {
    id: "dcw_032",
    fullName: "Aiden Scott",
    email: "aiden.scott@gmail.com",
    address: "400 S Grand Ave",
    zip: "90071",
    city: "Los Angeles",
    county: "Los Angeles",
    state: "California",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (213) 555-0119"
  },
  {
    id: "dcw_033",
    fullName: "Yasmin Abdel",
    email: "yasmin.abdel@care.com",
    address: "222 2nd Ave",
    zip: "10003",
    city: "New York",
    county: "New York",
    state: "New York",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (347) 555-0114"
  },
  {
    id: "dcw_034",
    fullName: "Brandon Miller",
    email: "brandon.miller@agency.com",
    address: "7000 Hollywood Blvd",
    zip: "90028",
    city: "Los Angeles",
    county: "Los Angeles",
    state: "California",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (323) 555-0142"
  },
  {
    id: "dcw_035",
    fullName: "Olivia Perez",
    email: "olivia.perez@gmail.com",
    address: "500 E 6th St",
    zip: "78701",
    city: "Austin",
    county: "Travis",
    state: "Texas",
    homePhone: "",
    workPhone: "",
    cellPhone: "+1 (512) 555-0164"
  }
];
